config/routes.rb
# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root to: 'root#index'

  get 'about-us', to: 'about#index', as: :about

  # Users
  get 'login', to: 'users#login'
  get 'signup', to: 'users#signup'
  get 'logout', to: 'users#logout'
  get 'profile', to: 'users#profile'

  # Articles
  # resources :articles
  get 'articles', to: 'articles#index', as: :articles
  get 'articles/new', to: 'articles#new', as: :articles_new
  post 'articles/new', to: 'articles#create'
  get 'articles/:id', to: 'articles#view', as: :articles_view
  get 'articles/:id/edit', to: 'articles#edit', as: :articles_edit
  patch 'articles/:id/edit', to: 'articles#update'
  delete 'articles/:id', to: 'articles#delete', as: :articles_delete
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  after_initialize :set_default_value
  before_save :set_url

  validates :title, presence: true
  validates :author, presence: true
  validates :body, presence: true
  validate :validate_model

  def generate_url_from_title
    title.downcase
         .gsub(' ', '-') # Replace spaces for -
         .gsub(/[^a-z0-9-]/, '') # Ignore any character that is not a letter or a number
         .gsub(/-{2,}/, '-') # Replace multiple consecutive hyphens with a single hyphen
         .gsub(/\A-+|-+\z/, '') # Remove extra hyphen at the begging and at the end
  end

  private

  def set_default_value
    self.author ||= 'Unknown'
    self.url ||= generate_url_from_title
  end

  def set_url
    self.url = generate_url_from_title
  end

  def validate_model
    return if !body.nil? && body.size > 5

    errors.add :body, 'is too short'
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  include PaginationHelper
  before_action :set_article, only: %i[view edit update delete]

  # GET /articles
  def index
    @articles_total = Article.count
    pagination = pagination_param(params[:page], params[:items_per_page], @articles_total)

    @page = pagination[:page]
    @items_per_page = pagination[:items_per_page]
    @total_pages = pagination[:total_pages]
    @articles = Article.offset(@page * @items_per_page).limit(@items_per_page).order(title: :asc)
  end

  # GET /articles/new
  def new
    @article = Article.new do |x|
      # x.title = 'bla'
      # x.author = 'author in do'
    end
    # @article.author = 'author after'
  end

  # POST /articles/new
  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to articles_path, notice: 'Article added'
    else
      render 'new'
    end
  end

  # GET /articles/1
  def view
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles/1/edit
  def update
    if @article.update(article_params)
      redirect_to articles_path, notice: 'Article saved'
    else
      render 'edit'
    end
  end

  # DELETE /articles/1
  def delete
    @article.destroy!
    redirect_to articles_path, notice: 'Article deleted'
  end

  private

  def valid_id?(val)
    true if val.is_a?(Numeric)

    Integer(val)
    true
  rescue ArgumentError
    false
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_article
    id = params[:id]

    # id is the real id
    if valid_id?(id)
      @article = Article.find(id)
      return nil
    end

    # check if id has the form of id-url
    id_split = id.split('-')
    new_id = id_split[0]
    if valid_id?(new_id)
      new_url = id_split.drop(1).join('-')

      @article = Article.find_by(id: new_id)
      unless @article
        render 'errors/404'
        return nil
      end

      render 'errors/404' if @article.url != new_url
      return nil
    end

    # search the article by url
    articles = Article.where url: id
    render 'errors/404' if articles.size != 1

    @article = articles[0]
  rescue ActiveRecord::RecordNotFound
    render 'errors/404'
  end

  # Only allow a list of trusted parameters through.
  def article_params
    params.require(:article).permit(:title, :author, :body)
  end
end

app/controllers/root_controller.rb
class RootController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def login
  end

  def signup
  end

  def logout
  end

  def profile
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pagination_helper.rb
module PaginationHelper
  extend ActiveSupport::Concern

  def pagination_param(page, items_per_page, total_items)
    page = page.present? ? page.to_i : 0
    items_per_page = items_per_page.present? ? items_per_page.to_i : 6

    total_pages = (total_items / items_per_page.to_f).ceil
    page = total_pages - 1 if page >= total_pages
    page = 0 if page.negative?

    {
      page:,
      items_per_page:,
      total_pages:
    }
  end
end

app/views/about/index.html.erb
<h1>About us</h1>

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>">
  <p>
    <strong>Title:</strong>
    <%= article.title %>
  </p>
  <p>
    <strong>Author:</strong>
    <%= article.author %>
  </p>
  <p>
    <strong>Body:</strong>
    <%= article.body %>
  </p>
</div>

app/views/articles/_form.html.erb
<script type="module">
  import 'tinymce';
</script>

<%= form_with model: article, data: { turbo: false }, html: { novalidate: true, autocomplete: "off" },
  url: url do |form| %>
  <fieldset>
    <div class="mb-3">
      <%= form.label :title, class: 'form-label' %>
      <%= form.text_field :title, class: "form-control #{article.errors[:title].size > 0 ? 'is-invalid' : ''}" %>
      <%= render partial: 'shared/form-error', locals: { errors: article.errors, type: :title } %>
    </div>
    <div class="mb-3">
      <%= form.label :author, class: 'form-label' %>
      <%= form.text_field :author, class: "form-control #{article.errors[:author].size > 0 ? 'is-invalid' : ''}" %>
      <%= render partial: 'shared/form-error', locals: { errors: article.errors, type: :author } %>
    </div>
    <div class="mb-3">
      <%= form.label :body, class: 'form-label' %>
      <%=
        form.text_area :body,
                       rows: 8,
                       tinymce: 'true',
                       class: "form-control #{article.errors[:body].size > 0 ? 'is-invalid' : ''}"
      %>
      <%= render partial: 'shared/form-error', locals: { errors: article.errors, type: :body } %>
    </div>
    <div class="mb-3 text-end">
      <% if defined?(back) %>
        <%= link_to 'Cancel', back, class: 'btn btn-danger' %>
      <% end %>
      <%= form.submit 'Submit', class: 'btn btn-primary' %>
    </div>
  </fieldset>
<% end %>

app/views/articles/_table-row.html.erb
<tr>
  <td><%= article.author %></td>
  <td><%= article.title %></td>
  <td class="fit">
    <%=
      link_to "<i class=\"fa-solid fa-eye fa-fw\"></i>".html_safe,
              articles_view_path(article.id),
              class: 'btn btn-primary'
    %>
    <%=
      link_to "<i class=\"fa-solid fa-pencil fa-fw\"></i>".html_safe,
              articles_edit_path(article.id),
              class: 'btn btn-primary'
    %>
    <%=
      button_to "<i class=\"fa-solid fa-trash-can fa-fw\"></i>".html_safe,
                articles_delete_path(article.id),
                method: :delete,
                class: 'btn btn-danger'
    %>
  </td>
</tr>

app/views/articles/_table.html.erb
<table class="table table-middle">
  <thead>
    <tr>
      <th>Author</th>
      <th>Title</th>
      <th class="fit">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @articles.each do |article| %>
      <%= render partial: 'table-row', locals: { article: article } %>
    <% end %>
  </tbody>
</table>

app/views/articles/edit.html.erb
<h1>
  Article: <%= @article.title %> <small>by <%= @article.author %></small>
</h1>

<%= render partial: 'form', locals: { article: @article, url: articles_edit_path, back: articles_path } %>

app/views/articles/index.html.erb
<script type="module">
  import '@pagination/display';
</script>

<div class="row align-items-center mb-2">
  <div class="col">
    <h1 class="mb-0">Articles</h1>
  </div>
  <div class="col-auto">
    <%= link_to 'New', articles_new_path, class: 'btn btn-primary' %>
  </div>
</div>

<%= render partial: 'shared/pagination-config' %>

<%=
  render partial: 'shared/pagination',
         locals: {
           page: @page,
           items_per_page: @items_per_page,
           total_pages: @total_pages,
           total: @articles_total,
           showTotal: false,
         }
%>

<%= render partial: 'table' %>

<%=
  render partial: 'shared/pagination',
         locals: {
           page: @page,
           items_per_page: @items_per_page,
           total_pages: @total_pages,
           total: @articles_total,
         }
%>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render partial: 'form', locals: { article: @article, url: articles_new_path, back: articles_path } %>

app/views/articles/view.html.erb
<h1>
  <%= @article.title %>
  <small>by <%= @article.author %></small>
</h1>

<div class="mb-3">
  <%= @article.body.html_safe %>
</div>

<div class="mb-3 text-end">
  <%= link_to 'Back', articles_path, class: 'btn btn-primary' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails Test</title>
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', 'data-turbo-track': 'reload' %>
    <%= javascript_importmap_tags %>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
      crossorigin="anonymous"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
      crossorigin="anonymous"
    ></script>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
      integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    <script
      src="https://cdn.tiny.cloud/1/9gqtzsnifwsdqr4bi5cv7u0zjc5dy3ckusc1p6r73ykikvp0/tinymce/6/tinymce.min.js"
      referrerpolicy="origin"
    ></script>
  </head>

  <body>
    <%= render 'shared/nav-bar' %>

    <div class="container mt-3">
      <%= yield %>
    </div>
  </body>
</html>

app/views/root/index.html.erb
<h1>Root</h1>

<%= link_to "About", about_path, class: "" %>

app/views/shared/_form-error.html.erb
<%
errors[type].each do |error|
%>
  <div class="invalid-feedback show">
    <%= errors.full_message(type, error) %>
  </div>
<%
end
%>

app/views/shared/_nav-bar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to 'Rails Test', root_path, class: 'navbar-brand' %>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Home', root_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'About', about_path, class: 'nav-link' %>
        </li>
      </ul>
      <ul class="navbar-nav mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Login', login_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign Up', signup_path, class: 'nav-link' %>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            User
          </a>
          <ul class="dropdown-menu dropdown-menu-lg-end">
            <li>
              <%= link_to 'Profile', profile_path, class: 'dropdown-item' %>
            </li>
            <li><hr class="dropdown-divider" /></li>
            <li>
              <%= link_to 'Logout', logout_path, class: 'dropdown-item' %>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_pagination-config.html.erb
<div class="row">
  <div class="col-auto">
    <form
      id="form-pagination-display"
      novalidate
      autocomplete="off"
      data-turbo="false"
      action="<%= articles_path %>"
      method="get"
    >
      <div class="mb-3">
        <label class="pe-3">Display</label>
        <select id="form-pagination-display-items_per_page" name="items_per_page" class="form-control">
          <%
          [6, 8, 12, 16].each do |x|
            %>
            <option value="<%= x %>" <%= x == @items_per_page ? 'selected="selected"' : '' %>>
              <%= x %>
            </option>
          <%
          end
        %>
        </select>
      </div>
    </form>
  </div>
  <div class="col"></div>
</div>

app/views/shared/_pagination.html.erb
<nav>
  <ul class="pagination justify-content-end mb-1">
    <li class="page-item <%= page <= 0 ? 'disabled' : '' %>">
      <%=
        link_to "<i class=\"fa-solid fa-chevron-left\"></i><i class=\"fa-solid fa-chevron-left\"></i>".html_safe,
                url_for(params.permit!.merge(page: 0)),
                class: 'page-link'
      %>
    </li>
    <li class="page-item <%= page <= 0 ? 'disabled' : '' %>">
      <%=
        link_to "<i class=\"fa-solid fa-chevron-left fa-fw\"></i>".html_safe,
                url_for(params.permit!.merge(page: page - 1)),
                class: 'page-link'
      %>
    </li>
    <%
    total_pages.times do |i|
    %>
      <li class="page-item">
        <%=
          link_to "#{i + 1}", url_for(params.permit!.merge(page: i)), class: "page-link #{i == page ? 'active' : ''}"
        %>
      </li>
    <%
    end
    %>
    <li class="page-item <%= page >= total_pages - 1 ? 'disabled' : '' %>">
      <%=
        link_to "<i class=\"fa-solid fa-chevron-right fa-fw\"></i>".html_safe,
                url_for(params.permit!.merge(page: page + 1)),
                class: 'page-link'
      %>
    </li>
    <li class="page-item <%= page >= total_pages - 1 ? 'disabled' : '' %>">
      <%=
        link_to "<i class=\"fa-solid fa-chevron-right\"></i><i class=\"fa-solid fa-chevron-right\"></i>".html_safe,
                url_for(params.permit!.merge(page: total_pages - 1)),
                class: 'page-link'
      %>
    </li>
  </ul>
  <% if !defined?(showTotal) || showTotal != false %>
    <div class="text-end mb-3">Total: <%= total %></div>
  <% end %>
</nav>

app/views/users/login.html.erb
<h1>Login</h1>

app/views/users/logout.html.erb
<h1>Logout</h1>

app/views/users/profile.html.erb
<h1>Profile</h1>

app/views/users/signup.html.erb
<h1>Sign Up</h1>